"""Rebuild CC0 piano runtime asset from the retained original recording.
Requires ffmpeg only. Does not access the network or synthesize noise.
"""
from pathlib import Path
import subprocess,json,hashlib,base64
HERE=Path(__file__).resolve().parent
FORUM=HERE.parents[2]
OUT=FORUM/'assets/music';OUT.mkdir(exist_ok=True)
source=HERE/'haunting-piano-original.mp3'
target=OUT/'haunting-piano-loop.mp3'
# Remove silent head/tail, normalize gently, crossfade the tail into the head.
# A[1..end] + A[0..1] crossfade closes at the same sample phase on each repeat.
filters='[0:a]atrim=start=1.45:end=55.30,asetpts=PTS-STARTPTS,loudnorm=I=-25:TP=-6:LRA=8,aresample=44100,asplit=2[a][b];[a][b]acrossfade=d=1:c1=tri:c2=tri,atrim=start=1:end=53.85,asetpts=PTS-STARTPTS[out]'
subprocess.run(['ffmpeg','-y','-v','error','-i',str(source),'-filter_complex',filters,'-map','[out]','-map_metadata','-1','-ar','44100','-ac','2','-codec:a','libmp3lame','-b:a','128k',str(target)],check=True)
metadata=dict(id='haunting-piano',title='Haunting piano',artist='Emma_MA',license='CC0-1.0',source='https://opengameart.org/content/haunting-piano',recording='https://opengameart.org/sites/default/files/haunting%20piano_0.mp3',licenseURL='https://creativecommons.org/publicdomain/zero/1.0/',checked='2026-09-21',sourceSHA256=hashlib.sha256(source.read_bytes()).hexdigest(),runtimeSHA256=hashlib.sha256(target.read_bytes()).hexdigest(),loopSeconds=52.85,processing='Trim 1.45–55.30s; -25 LUFS / -6 dBTP / LRA8; 1s circular linear crossfade; stereo 44.1kHz MP3 128kbps. No noise layers or additional samples.',asset='assets/music/haunting-piano-loop.mp3')
(HERE/'manifest.json').write_text(json.dumps(metadata,ensure_ascii=False,indent=2)+'\n')
payload={**metadata,'base64':base64.b64encode(target.read_bytes()).decode()}
# Classic lazy-loaded script works offline and file:// without fetch/CORS.
(OUT/'music-data.js').write_text('/* CC0: Emma_MA — Haunting piano. Generated by art/source/music/build_music.py. */\nwindow.WeimingMusicData='+json.dumps(payload,ensure_ascii=False,separators=(',',':'))+';\n')
print(target,len(target.read_bytes()),'bytes; embedded fallback generated.')
