"""Build local TTS excerpts from canonical case text. macOS say + ffmpeg.
No voice cloning, network calls or new story lines. OS voice redistribution rights
must be checked before public/commercial release (see NOTICE.md).
"""
from pathlib import Path
import json,re,html,subprocess,tempfile,hashlib
ROOT=Path(__file__).resolve().parents[5]
FORUM=ROOT/'src/forum_system'
# id, case, source kind/id, paragraph index, visual, direction label, voice
SPECS=[
 ('river-lantern','lantern','post','river',6,'lantern','逆水灯','Tingting'),
 ('missing-half','lantern','post','archive',3,'letter','缺页','Eddy (中文（中国大陆）)'),
 ('six-lights','lamplife','post','opening',3,'blackout','灯灭之前','Tingting'),
 ('left-record','lamplife','post','archive',3,'letter','被挤掉的一行','Eddy (中文（中国大陆）)'),
 ('mirror-turn','mirrorname','post','opening',2,'mirror','她没有转身','Tingting'),
 ('return-letter','wellpost','post','opening',0,'letter','回邮信','Tingting'),
 ('last-seat','homecoming','post','opening',3,'letter','最后一席','Eddy (中文（中国大陆）)'),
 ('red-contract','bridal','post','opening',4,'letter','红纸上的回答','Tingting'),
 ('road-bell','caravan','post','opening',4,'lantern','路尽处的铃','Eddy (中文（中国大陆）)'),
 ('snow-vigil','snow','post','opening',4,'candle','无人落座','Tingting'),
 ('curtain-shadow','shadowplay','post','opening',4,'shadow','落幕以后','Eddy (中文（中国大陆）)'),
 ('lamp-wire','lamplife','clue','trace',0,'blackout','灯台记录','Eddy (中文（中国大陆）)'),
 ('duty-note','lantern','clue','ledger',0,'letter','值班簿旁读','Eddy (中文（中国大陆）)'),
]
def plain(text):
 return re.sub(r'\s+',' ',html.unescape(re.sub('<[^>]+>',' ',text.replace('<br>','')))).strip()
def run(*args):return subprocess.run(args,check=True,capture_output=True,text=True).stdout
out=FORUM/'assets/voice-v6';out.mkdir(exist_ok=True)
readings=[]
for id,case,kind,source,index,visual,label,voice in SPECS:
 c=json.loads((ROOT/'cases/playable'/case/'case.json').read_text())
 item=next(p for p in c['posts'] if p['id']==source) if kind=='post' else c['clues'][source]
 text=plain(item['body'][index] if kind=='post' else item['text'])
 with tempfile.TemporaryDirectory(prefix='weiming-voice-') as d:
  aiff=Path(d)/'speech.aiff';mp3=out/(id+'.mp3')
  run('/usr/bin/say','-v',voice,'-r','165','-o',str(aiff),text)
  # A restrained phone-band treatment. No pitch shifting or loud startle sounds.
  run('ffmpeg','-y','-v','error','-i',str(aiff),'-af','highpass=f=115,lowpass=f=5700,loudnorm=I=-22:TP=-3:LRA=7,afade=t=in:d=0.08,apad=pad_dur=0.15','-ar','44100','-ac','1','-codec:a','libmp3lame','-b:a','96k',str(mp3))
  duration=float(run('ffprobe','-v','error','-show_entries','format=duration','-of','default=nw=1:nk=1',str(mp3)).strip())
 readings.append(dict(id=id,caseId=case,kind=kind,source=source,paragraph=index,visual=visual,label=label,title=item['title'],text=text,voice=voice,duration=round(duration,2),audio='assets/voice-v6/'+id+'.mp3',sha256=hashlib.sha256(mp3.read_bytes()).hexdigest()))
 print(id,round(duration,1),'seconds',flush=True)
manifest=dict(version=1,provenance='Local macOS system TTS / exact excerpts, not character recordings',readings=readings)
(FORUM/'presentation/readings.js').write_text('/* Generated by art/source/narrative/build_readings.py; exact original excerpts. */\nwindow.WeimingReadings = '+json.dumps(manifest,ensure_ascii=False,indent=2)+';\n')
(FORUM/'art/source/narrative/readings-manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
